language: java

jdk:
- oraclejdk8
#git strips the wrapper jar file so we have to force its downloaad during the build
sudo: false
before_install:
- chmod +x gradlew/wrapper/gradle-wrapper.jar
- git add -f gradle/wrapper/gradle-wrapper.jar

